sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - pwd

script:
  - "docker-compose run workspace bash -c
    'make -j4 -C /worktree/CXXtoXML
     && make -j4 -C /worktree/XcodeMLtoCXX
     && make -C /worktree/XcodeMLtoCXX check
     && make -C /worktree/tests/Compilability check'"
